spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dermatel_db
    username: dermatel
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 10MB
      max-request-size: 10MB
file:
  upload:
    dir: ./uploads

jwt:
  secret: d205b4b69c2ebd1950634feeb32eef9a7ee8beea3eac705bad19a3236c5c4c28
  expiration: 3600
