spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 10MB
      max-request-size: 10MB
file:
  upload:
    dir: ./uploads

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000

paymongo:
  api:
    url: https://api.paymongo.com
    key: ${PAYMONGO_API_KEY}