version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: dermatel
    restart: always
    environment:
      POSTGRES_DB: dermatel_db           # Database name
      POSTGRES_USER: dermatel            # Database user
      POSTGRES_PASSWORD: password        # Database password
    ports:
      - "5432:5432"                      # Map port 5432 on host to 5432 in the container
    volumes:
      - pg_data:/var/lib/postgresql/data # Persist data in the pg_data volume

volumes:
  pg_data:                                # Define a named volume for data persistence
